[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
backpointa = "58VzX9LtDZMqYkjN5BTEDQ512jGBHpJtUZ7WRHe47xFA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jd/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
